- Apri Amazon
  
- SE sito Amazon non risponde:
  - Vai alla Mondadori
    - Scegli sezione di ricerca   
  - FINCHE` non trovi un buon libro:
    - Cerca Libro
    - SE trovi libro:
        - Prendi Libro 
    - ALTRIMENTI SE finisci catalogo libri:
        - Cambia sezione
    - ALTRIMENTI:
        - Aggiungi buono Mondadori 
  
    - Vai in cassa
    - Seleziona metodo pagamento
    - SE paghi con carta: 
      - SE carta è carica:
        - Paga con carta
      - ALTRIMENTI:
        - cambia carta O carica carta
    - ALTRIMENTI SE paghi con contanti:
      - Paga con contanti

- ALTRIMENTI
  - Effettua login
  - SE ricordi password:
    - Accedi
  - ALTRIMENTI:
    - Recupera Password

  - Cerca la lamapada da tavolo che piace a Silvia
    - SE consegna è Prime:
       -  Aggiungi Lampada da tavolo al carrello
    - ALTRIMENTI:
      -  Cerca stilografica
      -  SE non sfora budget:
         -  Aggiungi strilografica al carrello
      -  ALTRIMENTI:
         - FINCHE` non trovi un buon libro: 
            - Cerca Libro
            - SE trovi libro:
              - Aggiungi Libro al carrello
            - ALTRIMENTI SE finisci catalogo libri:
              - Aggiungi buono amazon
              - Vai avanti

    - Vai al carrello
    - Seleziona metodo pagamento
    - SE la carta è carica:
      - Paga
    - ALTRIMENTI:
      - Carica carta O cambia metodo pagamento
    - Seleziona indirizzo fatturazione
    - Compra
    - Attendi regalo 